apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  labels:
    app: ledger-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: ledger-service
          image: babacar-niang/transaction-ledger-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ledger-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ledger-secrets
                  key: db-password
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: ledger-config
                  key: kafka-bootstrap-servers
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  selector:
    app: ledger-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-config
data:
  kafka-bootstrap-servers: "kafka:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: ledger-secrets
type: Opaque
stringData:
  db-username: ledger
  db-password: ledger
